<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>House Price Predictor</title>

    <!-- CSS STYLE SHEET -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>

<body class="bg-dark">
    <div class="container">
        <div class="row">
            <div class="card" style="width: 100%; height: 100%; margin-top: 50px;">
                <div class="card-header" style="text-align: center">
                    <h1>House Price Predictor</h1>
                </div>
                <div class="card-body">
                    <form method="post" action="" accept-charset="utf-8">

                        <div class="row">

                            <div class="col-md-6 form-group" style="text-align: center;">
                                <label for=""><b>Select the Location: </b></label>
                                <select class="selectpicker form-control" id="location" name="location" required="1">

                                    {% for location in locations %}
                                    <option value="{{ location }}">{{ location }}</option>
                                    {% endfor %}

                                </select>
                            </div>

                            <div class="col-md-6 form-group" style="text-align: center;">
                                <label for=""><b>Enter the BHK: </b></label>
                                <input type="text" class="form-control" id="bhk" name="bhk" placeholder="Enter BHK">
                            </div>

                            <div class="col-md-6 form-group" style="text-align: center;">
                                <label for=""><b>Enter Number of Bathrooms: </b></label>
                                <input type="text" class="form-control" id="bath" name="bath"
                                    placeholder="Enter Number of Bathrooms">
                            </div>

                            <div class="col-md-6 form-group" style="text-align: center;">
                                <label for=""><b>Enter Square Feet: </b></label>
                                <input type="text" class="form-control" id="total_sqft" name="total_sqft"
                                    placeholder="Enter Sqyare Feet">
                            </div>

                            <div class="col-md-12 form-control">
                                <button class="btn btn-primary form-control" onclick="send_data()">Predict
                                    Price</button>
                            </div>
                        </div>

                    </form>
                    <br>

                    <div class="col-md-12" style="text-align: center;">
                        <h3><span id="prediction"></span></h3>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <script>
        function form_handler(event) {
            event.preventDefault(); //Don't submit the form normally
        }

        function send_data() {
            document.querySelector('form').addEventListener("submit", form_handler);

            var fd = new FormData(document.querySelector('form'));

            var xhr = new XMLHttpRequest();

            xhr.open('POST', '/predict', true);
            document.getElementById("prediction").innerHTML = "Wait Prediction Price!.....";

            xhr.onreadystatechange = function () {
                if (xhr.readyState == XMLHttpRequest.DONE) {
                    document.getElementById("prediction").innerHTML = "Prediction : Rs. " + xhr.responseText;
                }
            };

            xhr.onload = function () { };
            xhr.send(fd);

        }
    </script>




    <!-- JQuerry, Propper.js and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
        integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
        crossorigin="anonymous"></script>


</body>

</html>
